### ISSUE TITLE
why use pdm-backend over setuptools?

### ISSUE THREAD

**Issue by deronnax** [pdm-project/pdm-backend#214]
Honest curiosity question: why use pdm-backend rather than setuptools? What are the benefit?
If I get an answer, I will make a PR to include it in the doc because I think that's a question many people have.

**Comment by frostming** [comment]
I built this backend initially to replace the many mysterious configurations of `setuptools`, think of `data_files`, `package_data`, `include_package_data` and `MANIFEST.in`, few people can tell the differences and know how to use them. And what's more, it used to be the only companion backend of PDM(it's no longer the case today).

`pdm-backend` provides sane defaults to support common package layouts, so that users don't need to configure anything or only need a few to make the whole thing work.
